# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  db:
      image: rest-with-asp-net-db
      command: mysqld --default-authentication-plugin=mysql_native_password
      restart: always
      build:
        context: .
        dockerfile: Sample.Repository/Dockerfile
      environment: 
        TZ: America/Minas Gerais
        MYSQL_ROOT_PASSWORD: docker
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
        MYSQL_DATABASE: rest_with_aspnet
      ports: 
        - 3308:3306
      networks:
        - blind-network
  sample:
    image: rest-with-asp-net
    build:
      context: .
      dockerfile: Sample.Api/Dockerfile
    environment: 
        TZ: America/Minas Gerais
        ASPNETCORE_ENVIRONMENT: Production 
    ports: 
      - 44300:80
    depends_on: 
      - db
    networks:
      - blind-network
networks: 
  blind-network: 
    driver: bridge