CREATE TABLE `roles` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`role` VARCHAR(7) NOT NULL DEFAULT 'MA00001',
	`description` VARCHAR(100) NOT NULL DEFAULT 'ACESSO BASICO/LEITURA AO SISTEMA',
	`enabled` BIT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (`id`),
	UNIQUE `role` (`role`)
)